version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  run-script:
    parameters:
      instance:
        type: integer
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg ca-certificates
            wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
            google-chrome --version

      - run:
          name: Install dependencies
          command: pip install --no-cache-dir -r requirements.txt

      - run:
          name: Run main.py 3 times in parallel (15 minutes max)
          command: |
            echo "Running instance << parameters.instance >>"
            timeout 15m python main.py &
            timeout 15m python main.py &
            timeout 15m python main.py &
            wait

workflows:
  version: 2
  run-matrix:
    jobs:
      - run-script:
          matrix:
            parameters:
              instance: [1,2]
